from Char import Char

data = [
    Char('1','一','yi4','UNO','Es un uno horizontal.'),
    Char('2','二','er4','DOS','Dos veces 1 es 2.'),
    Char('3','三','san1','TRES','Tres veces 1 es 3'),
    Char('4','四','si4','CUATRO','Boca con piernas.'),
    Char('5','五','wu3','CINCO',''),
    Char('6','六','liu4','SEIS','Chistera y patas.'),
    Char('7','七','qi1','SIETE','Como componente es cortar en dados.'),
    Char('8','八','ba1','OCHO','Es como un infinito acostado.'),
    Char('9','九','jiu2','NUEVE','Como componente es beisbol, ya que cada equipo tiene nueve jugadores'),
    Char('10','十','shi2','DIEZ','X es diez en números romanos, en Chino hay que girarlo. Como componente es aguja.'),
    Char('11','口','kou3','BOCA','Pictograma de una boca abierta. Como componente es boca, abertura o entrada de cueva.'),
    Char('12','日','ri4','DÍA','Pictograma de sol sonriente. Como componente es sol, día o lengua que se agita en una boca.'),
    Char('13','月','yue4','MES','Pictograma de luna sonriente (con ojos). Componente: luna, carne o parte del cuerpo.'),
    Char('14','田','tian2','CAMPO DE ARROZ', 'Pictograma campo de arroz. Componente: cerebro.'),
    Char('15','目','mu4','OJO','Pictograma ojo, la zona central es el iris. Componente: ojo y sol (cuando esta acostado)'),
    Char('16','古','gu3','ANTIGUO','Tumba antigua llena de telarañas con una cruz clavada. Componente: tumba o tumba antigua.'),
    Char('17','胡','hu2','IMPRUDENTE','La luna antigua es toda blanca, por lo que ilumina al 100%. La gente hace cosas imprudentes en esta ocasión, como los hombres lobo.'),
    Char('18','叶','ye4','HOJA','Los chinos son famosos por hacer medicamentos con hojas. Imagina un médico metiendote diez hojas por la boca.'),
    Char('19','吾','wu2','YO (literario)','Somos lo que pensamos, nuestra cabeza. Imagina una cabeza con 5 bocas (oidos, boca y agujeros nariz), eso somos.'),
    Char('20','朋','peng2','COMPAÑERO','Dios creo a Eva a partir de la costilla de Adán. Éste al ver a su compañera exclamó \' carne de mi carne\''),
    Char('21','明','ming2','CLARO','El claro sol da luz por la mañana y la clara luna da luz por la noche.'),
    Char('22','品','pin3','BIENES','Actualmente los bienes se producen en masa y la gente espera con la boca abiera a consumir cualquier cosa.'),
    Char('23','晶','jing1','CENTELLEANTE','Si colocamos un diamante al sol la luz se desdobla.'),
    Char('24','昌','chang1','PRÓSPERO','Un día soleado es un día próspero. Si tenemos dos soles, ¿Qué puede ser más prospero que eso?'),
    Char('25','唱','chang4','CANTAR','Una boca que no habla (director) y dos bocas con sus lenguas moviendose (coro).'),
    Char('26','早','zao3','TEMPRANO','Pictograma de un girasol. El sol sale temprano para dar rayos de sol al girasol.'),
    Char('27','旭','xu4','SOL NACIENTE','En Japón (el país del sol naciente) el béisbol ha llegado a ser muy popular.'),
    Char('28','世','shi4','GENERACIÓN','Una generación no es más que 30 años (10 + 10 + 10).'),
    Char('29','胃','wei4','ESTÓMAGO','La parte del cuerpo que alimenta a nuestro cerebro es el estómago.'),
    Char('30','旦','dan4','AMANECER','El sol saliendo del horizonte.'),
    Char('31','凹','ao1','CÓNCAVO','Una boca con un cráter'),
    Char('32','凸','tu1','CONVEXO',''),
    Char('33','自','zi4','UNO MISMO','Los chinos señalan a su nariz (esa gota que está entre nuestros ojos) para referirse a ellos. Nosotros señalamos a nuestro pecho.'),
    Char('34','白','bai2','BLANCO','El blanco es una mezcla de todos los colores juntos, si colocamos un prima en un rato de luz se puede comprobar. Así el blanco es una "gota de luz"'),
    Char('35','百','bai3','CIEN','El 99 cumpleaños se conoce como el "año blanco" porque el caracter que se obtiene al restarle 1 al número 100 es 99.'),
    Char('36','皂','zao4','JABÓN','Este jabón corta la grasa y devuelve el blanco original a la ropa.'),
    Char('37','旧','jiu4','VIEJO','Al igual que nosotros, cuando los días se hacen viejos necesitan un bastón para poder caminar.'),
    Char('38','中','zhong1','MEDIO','Un emperador de la Edad Media come con la boca tan abierta que necesita un bastón para mantenerla abierta y así no tener ni que masticar.'),
    Char('39','千','qian1','MIL','Exprimir la última gota de tinta para escribir los ceros que faltan para converir un diez en un diez mil.'),
    Char('40','舌','she2','LENGUA','Imagina diez mil personas deslenguadas que usan la misma lengua para poder hablar. Hacen fila para meterse la lengua en la boca y hablar.'),
    Char('41','升','sheng1','LITRO','Una nueva bebida compuesta de mil agujas que viene en una botella de un litro.'),
    Char('42','丸','wan2','PÍLDORA','Jugador de béisbol que lleva colgada en el cuello un frasco que contiene píldoras para doparte y ser más competitivo.'),
    Char('43','卜','bu3','ADIVINICACIÓN',''),
    Char('44','占','zhan1','',''),
    Char('45','上','zhang4','',''),
    Char('46','下','xia4','',''),
    Char('47','卡','ka3','',''),
    Char('48','卓','zhuo2','',''),
    Char('49','朝','chao2','',''),
    Char('50','嘲','chao3','',''),
    Char('51','只','zhi3','',''),
    Char('52','贝','bei4','',''),
    Char('53','帖','tie1','',''),
    Char('54','贞','zhen1','',''),
    Char('55','员','yuan2','',''),
    Char('56','儿','er2','',''),
    Char('57','几','ji3','',''),
    Char('58','见','jian4','',''),
    Char('59','元','yuan2','',''),
    Char('60','页','ye4','',''),
]
