from Char import Char

data = [
    Char('1', '一', 'yi4', 'UNO', 'Es un uno horizontal.'),
    Char('2', '二', 'er4', 'DOS', 'Dos veces 1 es 2.'),
    Char('3','三', 'san1', 'TRES', 'Tres veces 1 es 3'),
    Char('4','四', 'si4', 'CUATRO', 'Boca con piernas.'),
    Char('5','五', 'wu3', 'CINCO', ''),
    Char('6','六', 'liu4', 'SEIS', 'Chistera y patas.'),
    Char('7','七', 'qi1', 'SIETE', 'Como componente es cortar en dados.'),
    Char('8','八', 'ba1', 'OCHO', 'Es como un infinito acostado.'),
    Char('9','九', 'jiu2', 'NUEVE', 'Como componente es beisbol, ya que cada equipo tiene nueve jugadores'),
    Char('10','十', 'shi2', 'DIEZ', 'X es diez en números romanos, en Chino hay que girarlo. Como componente es aguja.'),
    Char('11','口', 'kou3', 'BOCA', 'Pictograma de una boca abierta. Como componente es boca, abertura o entrada de cueva.'),
    Char('12','日', 'ri4', 'DÍA', 'Pictograma de sol sonriente. Como componente es sol, día o lengua que se agita en una boca.'),
    Char('13','月', 'yue4', 'MES', 'Pictograma de luna sonriente (con ojos). Componente: luna, carne o parte del cuerpo.'),
    Char('14','田', 'tian2', 'CAMPO DE ARROZ', 'Pictograma campo de arroz. Componente: cerebro.'),
    Char('15','目', 'mu4', 'OJO', 'Pictograma ojo, la zona central es el iris. Componente: ojo y sol (cuando esta acostado)'),
    Char('16','古', 'gu3', 'ANTIGUO', 'Tumba antigua llena de telarañas con una cruz clavada. Componente: tumba o tumba antigua.'),
    Char('17','胡', 'gu3', 'IMPRUDENTE', 'La luna antigua es toda blanca, por lo que ilumina al 100%. La gente hace cosas imprudentes en esta ocasión, como los hombres lobo.'),
    Char('18','叶', 'gu3', 'HOJA', ''),
    Char('19','吾', 'gu3', 'YO (literario)', ''),
    Char('20','朋', 'gu3', 'COMPAÑERO', ''),
    Char('21', '一', 'yi4', 'UNO', 'Es un uno horizontal.'),
    Char('22', '二', 'er4', 'DOS', 'Dos veces 1 es 2.'),
    Char('23','三', 'san1', 'TRES', 'Tres veces 1 es 3'),
    Char('24','四', 'si4', 'CUATRO', 'Boca con piernas.'),
    Char('25','五', 'wu3', 'CINCO', ''),
    Char('26','六', 'liu4', 'SEIS', 'Chistera y patas.'),
    Char('27','七', 'qi1', 'SIETE', 'Como componente es cortar en dados.'),
    Char('28','八', 'ba1', 'OCHO', 'Es como un infinito acostado.'),
    Char('29','九', 'jiu2', 'NUEVE', 'Como componente es beisbol, ya que cada equipo tiene nueve jugadores'),
    Char('30','十', 'shi2', 'DIEZ', 'X es diez en números romanos, en Chino hay que girarlo. Como componente es aguja.'),
    Char('31','口', 'kou3', 'BOCA', 'Pictograma de una boca abierta. Como componente es boca, abertura o entrada de cueva.'),
    Char('32','日', 'ri4', 'DÍA', 'Pictograma de sol sonriente. Como componente es sol, día o lengua que se agita en una boca.'),
    Char('33','月', 'yue4', 'MES', 'Pictograma de luna sonriente (con ojos). Componente: luna, carne o parte del cuerpo.'),
    Char('34','田', 'tian2', 'CAMPO DE ARROZ', 'Pictograma campo de arroz. Componente: cerebro.'),
    Char('35','目', 'mu4', 'OJO', 'Pictograma ojo, la zona central es el iris. Componente: ojo y sol (cuando esta acostado)'),
    Char('36','古', 'gu3', 'ANTIGUO', 'Tumba antigua llena de telarañas con una cruz clavada. Componente: tumba o tumba antigua.'),
    Char('37','胡', 'gu3', 'IMPRUDENTE', 'La luna antigua es toda blanca, por lo que ilumina al 100%. La gente hace cosas imprudentes en esta ocasión, como los hombres lobo.'),
    Char('38','叶', 'gu3', 'HOJA', ''),
    Char('39','吾', 'gu3', 'YO (literario)', ''),
    Char('40','朋', 'gu3', 'COMPAÑERO', ''),
]
